source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target "Videoanalysis" do
 pod 'JKCategories', '~> 1.8.2'
 pod 'QMUIKit'
 pod 'HWPanModal', '~> 0.6.0'
 pod 'Yoga', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
 pod 'FMDB'
 pod 'MBProgressHUD'
 pod 'IQKeyboardManager', '~> 6.3.0'
 pod 'AFNetworking'
end
